# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\"L\n\x13\x43reateRecordRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0c\n\x04roll\x18\x04 \x01(\t\"\"\n\x14\x43reateRecordResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x1f\n\x11ReadRecordRequest\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\x12ReadRecordResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\"J\n\x13UpdateRecordRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\"\'\n\x14UpdateRecordResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x13\x44\x65leteRecordRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteRecordResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xff\x01\n\x0f\x44\x61tabaseService\x12;\n\x0c\x43reateRecord\x12\x14.CreateRecordRequest\x1a\x15.CreateRecordResponse\x12\x35\n\nReadRecord\x12\x12.ReadRecordRequest\x1a\x13.ReadRecordResponse\x12;\n\x0cUpdateRecord\x12\x14.UpdateRecordRequest\x1a\x15.UpdateRecordResponse\x12;\n\x0c\x44\x65leteRecord\x12\x14.DeleteRecordRequest\x1a\x15.DeleteRecordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATERECORDREQUEST']._serialized_start=18
  _globals['_CREATERECORDREQUEST']._serialized_end=94
  _globals['_CREATERECORDRESPONSE']._serialized_start=96
  _globals['_CREATERECORDRESPONSE']._serialized_end=130
  _globals['_READRECORDREQUEST']._serialized_start=132
  _globals['_READRECORDREQUEST']._serialized_end=163
  _globals['_READRECORDRESPONSE']._serialized_start=165
  _globals['_READRECORDRESPONSE']._serialized_end=226
  _globals['_UPDATERECORDREQUEST']._serialized_start=228
  _globals['_UPDATERECORDREQUEST']._serialized_end=302
  _globals['_UPDATERECORDRESPONSE']._serialized_start=304
  _globals['_UPDATERECORDRESPONSE']._serialized_end=343
  _globals['_DELETERECORDREQUEST']._serialized_start=345
  _globals['_DELETERECORDREQUEST']._serialized_end=378
  _globals['_DELETERECORDRESPONSE']._serialized_start=380
  _globals['_DELETERECORDRESPONSE']._serialized_end=419
  _globals['_DATABASESERVICE']._serialized_start=422
  _globals['_DATABASESERVICE']._serialized_end=677
# @@protoc_insertion_point(module_scope)
